apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate-${domain}
  namespace: cert-manager
spec:
  commonName: "*.${domain}"
  dnsNames:
    - ${domain}
    - "*.${domain}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: wildcard-${domain}-tls